baseURL = 'https://sivadotblog.github.io/'
languageCode = 'en-us'
title = 'SIvas Data platform Handbook'
theme = 'hugo-theme-relearn'
[params]
  disableLandingPageButton = true
  collapsibleMenu = true

