# Sample workflow for building and deploying a Hugo site to GitHub Pages
name: Deploy Hugo site to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  # Build job
  build:
    runs-on: ubuntu-20.04
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      HUGO_VERSION: 0.101.0
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true # Fetch Hugo themes (true OR recursive)
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      # - name: Setup Node.js to build theme
      #   uses: actions/setup-node@v1
      #   with:
      #     node-version: 17

      # - name: Build Geekdoc theme (1/2)
      #   working-directory: ./themes/hugo-geekdoc
      #   run: |
      #     npm install
      #     npm run build

      # - name: Build Geekdoc theme (2/2)
      #   working-directory: ./themes/hugo-geekdoc
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y asciidoctor

      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_Linux-64bit.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb

      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      # Update references
      - name: Initialize submodules
        run: git submodule update --init --recursive

      - name: Update submodule
        run: git submodule update --remote --merge

      - name: Commit changes
        run: |
          git config --global user.email "sivanandha@gmail.com"
          git config --global user.name "sivadotblog"
          git add .
          git commit -m "Update submodule"
          git push https://${{ GH_TOKEN }}@github.com/${{ github.repository }}

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v1
      - name: Build with Hugo
        run: |
          hugo \
            -D \
            --minify \
            --baseURL ${{ steps.pages.outputs.base_url }}
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./public

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-20.04
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
